@startuml

entity "Users" as user {
  + GUID : string
  --
  FullName : string
  PicturePath : string
}

entity "Roles" as role {
  + GUID : string
  --
  Name : string
}

entity "Apps" as application {
  + GUID : string
  --
  Name : string
  IconPath : string
  URL : string
}

entity "User_Role" as user_role {
  + UserGUID : string
  + RoleGUID : string
}

entity "Role_App" as role_application {
  + RoleGUID : string
  + ApplicationGUID : string
}

user ||..o{ user_role
role ||..o{ user_role
role ||..o{ role_application
application ||..o{ role_application

@enduml