@startuml

entity "User" as user {
  + GUID : string
  --
  FirstName : string
  LastName : string
  Picture : string
}

entity "Role" as role {
  + GUID : string
  --
  Name : string
}

entity "Application" as application {
  + GUID : string
  --
  Name : string
  Icon : string
  URL : string
}

entity "User_Role" as user_role {
  + UserGUID : string
  + RoleGUID : string
}

entity "Role_Application" as role_application {
  + RoleGUID : string
  + ApplicationGUID : string
}

user ||..o{ user_role
role ||..o{ user_role
role ||..o{ role_application
application ||..o{ role_application

@enduml